INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2001-01-04', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2004-03-12', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2014-04-25', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2009-05-22', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2008-01-30', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2020-01-04', (SELECT ID FROM CUSTOMER WHERE NAME = 'BigCo'));


INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2001-01-02', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2004-03-14', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2014-04-12', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'),  '2009-05-16', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2008-01-22', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2020-01-06', (SELECT ID FROM CUSTOMER WHERE NAME = 'TeatroCo'));


INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2001-01-02', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 1'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'),  '2004-03-14', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 1'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2014-04-12', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 1'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2009-05-16', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 2'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'),  '2008-01-22', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 2'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'),  '2020-01-06', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 2'));


INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2001-01-02', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 3'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2004-03-14', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 3'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2014-04-12', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 3'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2009-05-16', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 4'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2008-01-22', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 4'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2020-01-06', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 4'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2001-01-04', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 5'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2004-03-12', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 5'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2014-04-25', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 5'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2009-05-22', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 6'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2008-01-30', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 6'));

INSERT INTO BORDERO (ID, DATE, CUSTOMER_ID)
VALUES(nextval('bordero_sq'), '2020-01-04', (SELECT ID FROM CUSTOMER WHERE NAME = 'Otro Cliente 6'));
