INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'hamlet', 'Hamlet','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'as-like', 'As You Like It','comedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'othello', 'Othello','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay1', 'Otro Play 1','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'),  'otroplay2', 'Otro Play 2','comedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay3', 'Otro Play 3','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay4', 'Otro Play 4','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay5', 'Otro Play 5','comedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay6', 'Otro Play 6','comedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay7', 'Otro Play 7','tragedy');
INSERT INTO PLAY (ID, CODE, NAME, TYPE) VALUES (nextval('play_sq'), 'otroplay8', 'Otro Play 8','comedy');
